language: python
python:
  - "2.7"

env:
    - TOX_ENV=py27-hg2.6
    - TOX_ENV=py26-hg2.6
    - TOX_ENV=py27-hg3.1

before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis McTravis"
  - cp lib/python/mozilla_buildtools/test/hgrc ~/.hgrc

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_script:
  - tox -e py27-coveralls

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# please comment out this section in your personal fork!
notifications:
  irc:
    channels:
      - "irc.mozilla.org#callek"
    on_success: always
    on_failure: always
    template:
      - "\x02%{repository}\x02#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "\x02Change view\x02 : %{compare_url}"
      - "\x02Build details\x02 : %{build_url}"
      - "\x02Commit message\x02 : %{commit_message}"
